spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imagelite
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB